# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from team_nust_msgs/GoalInfo.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class GoalInfo(genpy.Message):
  _md5sum = "7ca7f41f373e0f0dcd0e485cfff71366"
  _type = "team_nust_msgs/GoalInfo"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
bool found
geometry_msgs/Point left_post
geometry_msgs/Point right_post
geometry_msgs/Point mid
geometry_msgs/Pose2D poseFromGoal
uint8 goal_type

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Pose2D
# This expresses a position and orientation on a 2D manifold.

float64 x
float64 y
float64 theta"""
  __slots__ = ['header','found','left_post','right_post','mid','poseFromGoal','goal_type']
  _slot_types = ['std_msgs/Header','bool','geometry_msgs/Point','geometry_msgs/Point','geometry_msgs/Point','geometry_msgs/Pose2D','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,found,left_post,right_post,mid,poseFromGoal,goal_type

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GoalInfo, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.found is None:
        self.found = False
      if self.left_post is None:
        self.left_post = geometry_msgs.msg.Point()
      if self.right_post is None:
        self.right_post = geometry_msgs.msg.Point()
      if self.mid is None:
        self.mid = geometry_msgs.msg.Point()
      if self.poseFromGoal is None:
        self.poseFromGoal = geometry_msgs.msg.Pose2D()
      if self.goal_type is None:
        self.goal_type = 0
    else:
      self.header = std_msgs.msg.Header()
      self.found = False
      self.left_post = geometry_msgs.msg.Point()
      self.right_post = geometry_msgs.msg.Point()
      self.mid = geometry_msgs.msg.Point()
      self.poseFromGoal = geometry_msgs.msg.Pose2D()
      self.goal_type = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_B12dB.pack(_x.found, _x.left_post.x, _x.left_post.y, _x.left_post.z, _x.right_post.x, _x.right_post.y, _x.right_post.z, _x.mid.x, _x.mid.y, _x.mid.z, _x.poseFromGoal.x, _x.poseFromGoal.y, _x.poseFromGoal.theta, _x.goal_type))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.left_post is None:
        self.left_post = geometry_msgs.msg.Point()
      if self.right_post is None:
        self.right_post = geometry_msgs.msg.Point()
      if self.mid is None:
        self.mid = geometry_msgs.msg.Point()
      if self.poseFromGoal is None:
        self.poseFromGoal = geometry_msgs.msg.Pose2D()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 98
      (_x.found, _x.left_post.x, _x.left_post.y, _x.left_post.z, _x.right_post.x, _x.right_post.y, _x.right_post.z, _x.mid.x, _x.mid.y, _x.mid.z, _x.poseFromGoal.x, _x.poseFromGoal.y, _x.poseFromGoal.theta, _x.goal_type,) = _struct_B12dB.unpack(str[start:end])
      self.found = bool(self.found)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_B12dB.pack(_x.found, _x.left_post.x, _x.left_post.y, _x.left_post.z, _x.right_post.x, _x.right_post.y, _x.right_post.z, _x.mid.x, _x.mid.y, _x.mid.z, _x.poseFromGoal.x, _x.poseFromGoal.y, _x.poseFromGoal.theta, _x.goal_type))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.left_post is None:
        self.left_post = geometry_msgs.msg.Point()
      if self.right_post is None:
        self.right_post = geometry_msgs.msg.Point()
      if self.mid is None:
        self.mid = geometry_msgs.msg.Point()
      if self.poseFromGoal is None:
        self.poseFromGoal = geometry_msgs.msg.Pose2D()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 98
      (_x.found, _x.left_post.x, _x.left_post.y, _x.left_post.z, _x.right_post.x, _x.right_post.y, _x.right_post.z, _x.mid.x, _x.mid.y, _x.mid.z, _x.poseFromGoal.x, _x.poseFromGoal.y, _x.poseFromGoal.theta, _x.goal_type,) = _struct_B12dB.unpack(str[start:end])
      self.found = bool(self.found)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_B12dB = struct.Struct("<B12dB")
