class CommMessageTypes:
  MEMORY = 0
  LOG_TEXT = 1
  TOP_IMAGE = 2
  BOTTOM_IMAGE = 3
  FOOTSTEPS = 4
  PF_STATES = 5
  OCCUPANCY_GRID = 6
  KNOWN_LANDMARKS = 7
  UNKNOWN_LANDMARKS = 8
  NIHA_COGNITION_HEADER = 9
  NIHA_COGNITION_DATA = 10
  USER_CMD = 11
