#!/bin/bash

set -eu
export scriptPath=$(echo $0 | sed "s|^\.\./|`pwd`/../|" | sed "s|^\./|`pwd`/|")
export baseDir=$(dirname ${scriptPath})

if [ "$(whoami)" != "root" ]; then
  # We are still user nao  
  
  # Create team nust directory
  mkdir -p /home/nao/team_nust/config

  # Create logs dir for logger
  mkdir -p /home/nao/team_nust/logs

  # Copy wireless profiles
  cp -r ${baseDir}/Robot/Profiles /home/nao/team_nust

  # Add /home/nao to search path (.profile is needed by putty? and .bashrc for bush)
  cp ${baseDir}/profile /home/nao/.profile
  cp ${baseDir}/profile /home/nao/.bashrc

  # Add commands to /home/nao/team_nust/bin
  mkdir -p /home/nao/team_nust/bin
  cp -R ${baseDir}/bin/* /home/nao/team_nust/bin
  
  # Continue as root
  echo "Please enter password for user 'root' (usually also 'root')."
  python -c 'import pty; pty.spawn(("/bin/su", "-c", "${scriptPath}"))'
else
  # Now we are root

  echo "Remounting"
  # if install is executed on a installed robot, / is read-only, therefore remount it,
  # otherwise this line will have no effect
  #mount -n -o remount,rw /
  
  # Change name
  cp ${baseDir}/Robot/hostname /etc/hostname
  python team_nust/bin/setRobotName.py $(cat /etc/hostname) | grep -v '[I]'

  # Make sudo work
  cp -f ${baseDir}/sudoers /etc
  chmod 440 /etc/sudoers
  chown root:root /etc/sudoers
  mkdir -p /var/db

  # Copy wireless-tools
  #cp ${baseDir}/wireless-tools/* /usr/bin/
	
  # Install newer libstdc++
  # cp ${baseDir}/libstdc++.so.6.0.20 /usr/lib
  # chmod 777 /usr/lib/libstdc++.so.6.0.20
  # ln -sf /usr/lib/libstdc++.so.6.0.20 /usr/lib/libstdc++.so.6
  # ln -sf /usr/lib/libstdc++.so.6.0.20 /usr/lib/libstdc++.so
  
  # cp ${baseDir}/libc-2.23.so /usr/lib
  # chmod 777 /usr/lib/libc-2.23.so
  # ln -sf /usr/lib/libc-2.23.so /usr/lib/libc.so.6

  # Speed up boot process
  if [ -f /usr/libexec/hal-prestarter ] ; then
    mv -n /usr/libexec/hal-prestarter /usr/libexec/hal-prestarter.org
  fi
  echo "#!/bin/sh" > /usr/libexec/hal-prestarter
  chmod +x /usr/libexec/hal-prestarter

  # wpa_supplicant
  cp ${baseDir}/Robot/wired /etc/init.d
  cp ${baseDir}/Robot/wireless /etc/init.d

  rc-update add wired boot
  rc-update add wireless boot

  echo "Setting hostname config"
  # Do not verify remote hostname via DNS
  if [ ! -f "/etc/ssh.conf/sshd_config" -o -z "$(grep "UseDNS no" "/etc/ssh.conf/sshd_config" 2>/dev/null)" ]; then
    echo "UseDNS no" >> "/etc/ssh.conf/sshd_config"
  fi

  echo "Setting timezone"
  # Set the timezone and localtime
  cp /usr/share/zoneinfo/Asia/Karachi /etc/localtime
  echo "Asia/Karachi" > /etc/timezone
  
  # Save original naoqi autoload file (but do not overwrite if backup already exists) and install B-Human's
  if [ ! -f /etc/naoqi/autoload.org ] ; then
    cp -n /etc/naoqi/autoload.ini /etc/naoqi/autoload.org
  fi
  #cp ${baseDir}/autoload.tnust /etc/naoqi/autoload.ini
  #/home/nao/team_nust/bin/toteamnust

  # Remove all services not needed
  rc-update >${baseDir}/temp
  for i in crash-report-uploader proxydaemon vsftpd nginx naopathe laser bootprogress_0 bootprogress_25 bootprogress_50 bootprogress_75 bootprogress_100 avahi-daemon lircd bluetooth hwclock sysctl local urandom termencoding netmount mtab sysklogd savecache firewall_mode ofono pulseaudio qimessaging-json udev-postmount
  do
    if [ ! -z "$(grep "$i |" ${baseDir}/temp)" ]; then
      rc-update del $(echo "$(grep "$i |" ${baseDir}/temp)" | sed "s%[ ]*\([^ ]*\) |[ ]*\([^ ]*\).*%\1 \2%")
    fi
  done

  # Load sshd later
  #rc-update add sshd
  
  # Install alternative modules
  # cp -r ${baseDir}/kernel/2.6.33.9-rt31-aldebaran-rt /lib/modules
  
  #sync

  #echo "[INFO] rebooting"
  #reboot
fi
