// Generated by gencpp from file team_nust_msgs/BallInfo.msg
// DO NOT EDIT!


#ifndef TEAM_NUST_MSGS_MESSAGE_BALLINFO_H
#define TEAM_NUST_MSGS_MESSAGE_BALLINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace team_nust_msgs
{
template <class ContainerAllocator>
struct BallInfo_
{
  typedef BallInfo_<ContainerAllocator> Type;

  BallInfo_()
    : header()
    , camera(0)
    , found(false)
    , pos()
    , world_pos()
    , vel()
    , world_vel()
    , image()
    , age(0.0)
    , radius(0.0)  {
    }
  BallInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , camera(0)
    , found(false)
    , pos(_alloc)
    , world_pos(_alloc)
    , vel(_alloc)
    , world_vel(_alloc)
    , image(_alloc)
    , age(0.0)
    , radius(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _camera_type;
  _camera_type camera;

   typedef uint8_t _found_type;
  _found_type found;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _pos_type;
  _pos_type pos;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _world_pos_type;
  _world_pos_type world_pos;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _vel_type;
  _vel_type vel;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _world_vel_type;
  _world_vel_type world_vel;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _image_type;
  _image_type image;

   typedef float _age_type;
  _age_type age;

   typedef float _radius_type;
  _radius_type radius;




  typedef boost::shared_ptr< ::team_nust_msgs::BallInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::team_nust_msgs::BallInfo_<ContainerAllocator> const> ConstPtr;

}; // struct BallInfo_

typedef ::team_nust_msgs::BallInfo_<std::allocator<void> > BallInfo;

typedef boost::shared_ptr< ::team_nust_msgs::BallInfo > BallInfoPtr;
typedef boost::shared_ptr< ::team_nust_msgs::BallInfo const> BallInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::team_nust_msgs::BallInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::team_nust_msgs::BallInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace team_nust_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'team_nust_msgs': ['/home/muptii/Documents/robocup/team-nust-robocup-v2/resources/team_nust_nao_interface_ws/src/team_nust_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'humanoid_nav_msgs': ['/opt/ros/indigo/share/humanoid_nav_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::team_nust_msgs::BallInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::team_nust_msgs::BallInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::team_nust_msgs::BallInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::team_nust_msgs::BallInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::team_nust_msgs::BallInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::team_nust_msgs::BallInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::team_nust_msgs::BallInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f99f7385aa73a1572aa87b070548316e";
  }

  static const char* value(const ::team_nust_msgs::BallInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf99f7385aa73a157ULL;
  static const uint64_t static_value2 = 0x2aa87b070548316eULL;
};

template<class ContainerAllocator>
struct DataType< ::team_nust_msgs::BallInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "team_nust_msgs/BallInfo";
  }

  static const char* value(const ::team_nust_msgs::BallInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::team_nust_msgs::BallInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint8 camera\n\
bool found\n\
geometry_msgs/Point pos\n\
geometry_msgs/Point world_pos\n\
geometry_msgs/Point vel\n\
geometry_msgs/Point world_vel\n\
geometry_msgs/Point image\n\
float32 age\n\
float32 radius\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::team_nust_msgs::BallInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::team_nust_msgs::BallInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.camera);
      stream.next(m.found);
      stream.next(m.pos);
      stream.next(m.world_pos);
      stream.next(m.vel);
      stream.next(m.world_vel);
      stream.next(m.image);
      stream.next(m.age);
      stream.next(m.radius);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BallInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::team_nust_msgs::BallInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::team_nust_msgs::BallInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "camera: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.camera);
    s << indent << "found: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.found);
    s << indent << "pos: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.pos);
    s << indent << "world_pos: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.world_pos);
    s << indent << "vel: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.vel);
    s << indent << "world_vel: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.world_vel);
    s << indent << "image: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
    s << indent << "age: ";
    Printer<float>::stream(s, indent + "  ", v.age);
    s << indent << "radius: ";
    Printer<float>::stream(s, indent + "  ", v.radius);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEAM_NUST_MSGS_MESSAGE_BALLINFO_H
