// Generated by gencpp from file team_nust_msgs/BehaviorInfo.msg
// DO NOT EDIT!


#ifndef TEAM_NUST_MSGS_MESSAGE_BEHAVIORINFO_H
#define TEAM_NUST_MSGS_MESSAGE_BEHAVIORINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace team_nust_msgs
{
template <class ContainerAllocator>
struct BehaviorInfo_
{
  typedef BehaviorInfo_<ContainerAllocator> Type;

  BehaviorInfo_()
    : header()
    , name()
    , fsm_state()
    , initiated(false)
    , running(false)
    , paused(false)
    , finished(false)
    , config()  {
    }
  BehaviorInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , name(_alloc)
    , fsm_state(_alloc)
    , initiated(false)
    , running(false)
    , paused(false)
    , finished(false)
    , config(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _fsm_state_type;
  _fsm_state_type fsm_state;

   typedef uint8_t _initiated_type;
  _initiated_type initiated;

   typedef uint8_t _running_type;
  _running_type running;

   typedef uint8_t _paused_type;
  _paused_type paused;

   typedef uint8_t _finished_type;
  _finished_type finished;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _config_type;
  _config_type config;




  typedef boost::shared_ptr< ::team_nust_msgs::BehaviorInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::team_nust_msgs::BehaviorInfo_<ContainerAllocator> const> ConstPtr;

}; // struct BehaviorInfo_

typedef ::team_nust_msgs::BehaviorInfo_<std::allocator<void> > BehaviorInfo;

typedef boost::shared_ptr< ::team_nust_msgs::BehaviorInfo > BehaviorInfoPtr;
typedef boost::shared_ptr< ::team_nust_msgs::BehaviorInfo const> BehaviorInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::team_nust_msgs::BehaviorInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::team_nust_msgs::BehaviorInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace team_nust_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'team_nust_msgs': ['/home/muptii/Documents/robocup/team-nust-robocup-v2/resources/team_nust_nao_interface_ws/src/team_nust_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'humanoid_nav_msgs': ['/opt/ros/indigo/share/humanoid_nav_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::team_nust_msgs::BehaviorInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::team_nust_msgs::BehaviorInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::team_nust_msgs::BehaviorInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::team_nust_msgs::BehaviorInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::team_nust_msgs::BehaviorInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::team_nust_msgs::BehaviorInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::team_nust_msgs::BehaviorInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57de5cc9489d08ac59be4fbd5d66a023";
  }

  static const char* value(const ::team_nust_msgs::BehaviorInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57de5cc9489d08acULL;
  static const uint64_t static_value2 = 0x59be4fbd5d66a023ULL;
};

template<class ContainerAllocator>
struct DataType< ::team_nust_msgs::BehaviorInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "team_nust_msgs/BehaviorInfo";
  }

  static const char* value(const ::team_nust_msgs::BehaviorInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::team_nust_msgs::BehaviorInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
string name\n\
string fsm_state\n\
bool initiated\n\
bool running\n\
bool paused\n\
bool finished\n\
string config\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::team_nust_msgs::BehaviorInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::team_nust_msgs::BehaviorInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.name);
      stream.next(m.fsm_state);
      stream.next(m.initiated);
      stream.next(m.running);
      stream.next(m.paused);
      stream.next(m.finished);
      stream.next(m.config);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BehaviorInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::team_nust_msgs::BehaviorInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::team_nust_msgs::BehaviorInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "fsm_state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.fsm_state);
    s << indent << "initiated: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.initiated);
    s << indent << "running: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.running);
    s << indent << "paused: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.paused);
    s << indent << "finished: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.finished);
    s << indent << "config: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.config);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEAM_NUST_MSGS_MESSAGE_BEHAVIORINFO_H
