// Generated by gencpp from file team_nust_msgs/LocalizationState.msg
// DO NOT EDIT!


#ifndef TEAM_NUST_MSGS_MESSAGE_LOCALIZATIONSTATE_H
#define TEAM_NUST_MSGS_MESSAGE_LOCALIZATIONSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace team_nust_msgs
{
template <class ContainerAllocator>
struct LocalizationState_
{
  typedef LocalizationState_<ContainerAllocator> Type;

  LocalizationState_()
    : header()
    , robot_localized(false)
    , position_confidence(0)
    , side_confidence(0)
    , robot_on_side_line(false)
    , localize_with_last_known(false)
    , landmarks_found(false)  {
    }
  LocalizationState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , robot_localized(false)
    , position_confidence(0)
    , side_confidence(0)
    , robot_on_side_line(false)
    , localize_with_last_known(false)
    , landmarks_found(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _robot_localized_type;
  _robot_localized_type robot_localized;

   typedef int32_t _position_confidence_type;
  _position_confidence_type position_confidence;

   typedef int32_t _side_confidence_type;
  _side_confidence_type side_confidence;

   typedef uint8_t _robot_on_side_line_type;
  _robot_on_side_line_type robot_on_side_line;

   typedef uint8_t _localize_with_last_known_type;
  _localize_with_last_known_type localize_with_last_known;

   typedef uint8_t _landmarks_found_type;
  _landmarks_found_type landmarks_found;




  typedef boost::shared_ptr< ::team_nust_msgs::LocalizationState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::team_nust_msgs::LocalizationState_<ContainerAllocator> const> ConstPtr;

}; // struct LocalizationState_

typedef ::team_nust_msgs::LocalizationState_<std::allocator<void> > LocalizationState;

typedef boost::shared_ptr< ::team_nust_msgs::LocalizationState > LocalizationStatePtr;
typedef boost::shared_ptr< ::team_nust_msgs::LocalizationState const> LocalizationStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::team_nust_msgs::LocalizationState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::team_nust_msgs::LocalizationState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace team_nust_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'team_nust_msgs': ['/home/sensei/team-nust-robocup/resources/team_nust_nao_interface_ws/src/team_nust_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'humanoid_nav_msgs': ['/opt/ros/indigo/share/humanoid_nav_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::team_nust_msgs::LocalizationState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::team_nust_msgs::LocalizationState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::team_nust_msgs::LocalizationState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::team_nust_msgs::LocalizationState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::team_nust_msgs::LocalizationState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::team_nust_msgs::LocalizationState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::team_nust_msgs::LocalizationState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6443aeeb1985422e92a70b31dbb67942";
  }

  static const char* value(const ::team_nust_msgs::LocalizationState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6443aeeb1985422eULL;
  static const uint64_t static_value2 = 0x92a70b31dbb67942ULL;
};

template<class ContainerAllocator>
struct DataType< ::team_nust_msgs::LocalizationState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "team_nust_msgs/LocalizationState";
  }

  static const char* value(const ::team_nust_msgs::LocalizationState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::team_nust_msgs::LocalizationState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
bool robot_localized\n\
int32 position_confidence\n\
int32 side_confidence\n\
bool robot_on_side_line\n\
bool localize_with_last_known\n\
bool landmarks_found\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::team_nust_msgs::LocalizationState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::team_nust_msgs::LocalizationState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.robot_localized);
      stream.next(m.position_confidence);
      stream.next(m.side_confidence);
      stream.next(m.robot_on_side_line);
      stream.next(m.localize_with_last_known);
      stream.next(m.landmarks_found);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocalizationState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::team_nust_msgs::LocalizationState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::team_nust_msgs::LocalizationState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "robot_localized: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.robot_localized);
    s << indent << "position_confidence: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position_confidence);
    s << indent << "side_confidence: ";
    Printer<int32_t>::stream(s, indent + "  ", v.side_confidence);
    s << indent << "robot_on_side_line: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.robot_on_side_line);
    s << indent << "localize_with_last_known: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.localize_with_last_known);
    s << indent << "landmarks_found: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.landmarks_found);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEAM_NUST_MSGS_MESSAGE_LOCALIZATIONSTATE_H
