#!/bin/sh
scriptPath=$(echo $0 | sed "s|^\.\./|`pwd`/../|" | sed "s|^\./|`pwd`/|")
basePath=$(dirname ${scriptPath})
currPath=$(pwd)
cd "${basePath}"
chmod 400 ../config/Keys/id_rsa_nao
ssh -i ../config/Keys/id_rsa_nao -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet nao@$1
cd "${currPath}"
